### PR TITLE
Reduce sum

### PR DESCRIPTION
**Pull request by bbbales2**
Moving this pull from: https://github.com/rmcelreath/cmdstan_map_rect_tutorial/pull/5

I made some more changes to the tutorial. It's targeting cmdstanr now. I'd like to wait until we have the release candidate to finish it up (render as html, etc).

@wds15, I got lazy when merging this and deleted two sections you wrote.

```
The first three arguments of the reducer function must always be
present. These encode the start and end index of the partial sum as
well as a slice of the entire data over which the reduction is to
be performed. Any additional arguments are optional. These optional
arguments are shared (read-only) among all computations.
```

```
In case you turn this into a multi-level model where you introduce
groups of data for which you fit group specific parameters, then it is
often helpful to perform the slicing over the groups and use as
slicing argument of `reduce_sum` the group parameters themselves. This
leads to a more efficient parallelization, since the sliced argument
only gets doubled in memory while the shared arguments will be copied
as many times as there are splits of the large sum.
```

Mostly I deleted them cause I was feeling tired and too lazy to incorporate them back into the new text. I'm leaving them here for now.

Re: the first, in this latest version of the tutorial I defer even explaining the interface very much (I just link back to the manual). Keeps it shorter and more focused on just getting people up and running.

Re: the second, again, I was just keeping it simple and so left it out. This could go in an expanded section or something.

Both could definitely go back in, it would just take a little work.

### CODE REVIEW

**Comment by bbbales2** [comment]
@wds15, @mitzimorris how do we put this up as a case study? Also this is ready to check (rendered .html attached)

**Comment by wds15** [comment]
case study sounds good to me. @mitzimorris ?

**Comment by mitzimorris** [comment]
case studies are part of the stan-dev.github.io repo - 

1. update Case Study index page: `users/documentation/case-studies.md`
2. add rendered case study html to directory `users/documentation/case-studies`

optional:  add case study code into repo example-models under directory `knitr`

**Comment by mitzimorris** [comment]
I can do this if you'd like me to.

the stan-dev.github.io repo will be republished automatically when you push to master.  
see - https://github.com/stan-dev/stan-dev.github.io/wiki/Using-the-Jeykll-Based-Website

**Comment by mitzimorris** [comment]
this is great!
one comment: section "Building and Running the model" - link CmdStanR to CmdStanR home page
https://mc-stan.org/cmdstanr/

I will write a CmdStanPy companion.

**Comment by bbbales2** [comment]
@mitzimorris I added the link. Yeah, if you wanna take this stuff and put it in the case studies repo I'd appreciate it!

**Comment by mitzimorris** [comment]
done!
https://mc-stan.org/users/documentation/case-studies/reduce_sum_tutorial.html
https://github.com/stan-dev/example-models/tree/master/knitr/reduce-sum

**Comment by wds15** [comment]
@bbbales2 sorry for catching this late... but I don't think that the current recommendation with how to utilise the cores is best. The tutorial suggests to use all 8 cores to a given chain and run the 4 chains in sequence. Since the within-chain parallelism is usually less efficient as compared to running multiple chains. Thus, I would recommend people on a 8 core machine to run the 4 chains in parallel and give each chain 2 cores. That should give you the best speedup in this setting.

Maybe we can at a later point recommend people in such a setting to over-subscribe cores - by running 4 chains in parallel and give each 3 cores. Doing so may be a good thing whenever one of the chains finishes early... but we can explore that later.

Do you mind if I make that change?

**Comment by bbbales2** [comment]
> Do you mind if I make that change?

Fair point. It actually works on this model, but I guess we wouldn't expect it to work elsewhere.

I think you're right that we should just do the recommended thing out of the gate, and the recommended thing should still be multiple chains. Feel free to make the change and push to master. I'll re-render the html later.

**Comment by bbbales2** [comment]
(And if you don't get around to it I'll just make the changes and run the benchmarks)

(Or if you want to make the changes and re-render that's the fine too -- remember to update the date)

**Comment by wds15** [comment]
The PR is up. Can you please rerun with your 8 core machine? Thanks.

**Pull request merged**
